name: Push Tests

on:
  push:
  workflow_dispatch:

jobs:
  pr-tests:
    uses: ./.github/workflows/pr-tests.yml

  build-publish:
    needs: pr-tests
    uses: ./.github/workflows/build-publish.yml
    with:
      publish: ${{ github.ref == 'refs/heads/master' }}
    secrets: inherit
